apiVersion: "spec.keptn.sh/0.2.2"
kind: "Shipyard"
metadata:
  name: "shipyard"
spec:
  stages:
    - name: "demo"
      sequences:
        - name: "hello"
          tasks:
            - name: "hello-world"